# Generated by Django 5.1.6 on 2025-02-26 21:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="manufacrturer",
            new_name="manufacturer",
        ),
        migrations.RenameField(
            model_name="driver",
            old_name="licence_number",
            new_name="license_number",
        ),
    ]
